name: filter_bar
description: filter_bar Library for Flutter, Easily create a filter bar.
version: 0.0.1
homepage:
issue_tracker:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

